#!/bin/bash

# Openconnect command-line script for connecting to the City of Long Beach's VPN servers
# from Debian-Ubuntu-derived Linux distro's.
#
# This script adapted from Jeff Sterns's script found at
#    http://www.socsci.uci.edu/~jstern/uci_vpn_ubuntu/ubuntu-openconnect-uci-instructions.html

VPNGRP=CLB

# your employee ID/login (all lower-case)
VPNUSER=alchave

# =============================================================================
# you shouldn't have to change anything below here
VPNURL=https://clbvpn1.ci.long-beach.ca.us
VPNSCRIPT=/usr/share/vpnc-scripts/vpnc-script

sudo openvpn --mktun --dev tun1 && \
sudo ifconfig tun1 up && \
sudo /usr/sbin/openconnect -s $VPNSCRIPT $VPNURL --user=$VPNUSER --authgroup=$VPNGRP --interface=tun1
sudo ifconfig tun1 down
